import { useEffect, useRef, useState } from 'react';
import { ArrowRight, CaretDown, CaretRight, CheckCircle, EnvelopeSimple, Eye, EyeSlash, PlayCircle, SignOut, Tag, UploadSimple, Users, X } from '@phosphor-icons/react';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/inter/700.css';
import { parseConnections, filterPeople, initialPeople, initialTags } from './data.js';

const routes = { home: 'Home', signin: 'Sign in', register: 'Register', dashboard: 'Dashboard' };
function getRoute() { return Object.hasOwn(routes, location.hash.slice(1)) ? location.hash.slice(1) : 'home'; }
function Logo({ small = false }) { return <a href="#home" className={`logo ${small ? 'small' : ''}`} aria-label="Linktag home"><img src="/assets/linktag.svg" alt="" />Linktag</a>; }
function Avatar({ person, large = false }) { return <span className={`avatar tone-${person.id % 4} ${large ? 'large' : ''}`} aria-hidden="true">{person.firstName[0]}{person.lastName[0]}</span>; }
function Button({ children, variant = '', ...props }) { return <button className={`button ${variant}`} {...props}>{children}</button>; }
function Modal({ title, children, onClose, wide = false }) {
  const ref = useRef(null);
  useEffect(() => { const dialog = ref.current; dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog ref={ref} className={`modal ${wide ? 'wide' : ''}`} aria-labelledby="modal-title" onCancel={onClose} onClick={e => { if (e.target === ref.current) onClose(); }}><div className="modal-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21} /></button></div>{children}</dialog>;
}
function Password({ label, name, autoComplete, minLength, placeholder = 'Enter your password' }) {
  const [visible, setVisible] = useState(false);
  return <label className="field">{label}<span className="password-wrap"><input type={visible ? 'text' : 'password'} name={name} autoComplete={autoComplete} minLength={minLength} placeholder={placeholder} required /><button type="button" aria-label={`${visible ? 'Hide' : 'Show'} ${label.toLowerCase()}`} onClick={() => setVisible(!visible)}>{visible ? <EyeSlash size={19} /> : <Eye size={19} />}</button></span></label>;
}
function Home({ onInfo }) {
  return <div className="home-page"><section className="home-dark"><header className="home-header"><Logo /><nav aria-label="Main navigation"><a href="#signin">Sign in</a><a href="#register" className="button">Create account</a></nav></header><main className="hero"><div className="hero-copy"><p className="eyebrow">A clearer view of your network</p><h1>Your network.<br />The right people.</h1><p className="hero-description">Find the connections that matter. Upload your LinkedIn CSV, choose your role tags, and explore your matches.</p><div className="hero-actions"><a href="#register" className="button">Get started <ArrowRight size={18} /></a><a className="text-action" href="#how-it-works" onClick={e => { e.preventDefault(); document.getElementById('how-it-works').scrollIntoView({ behavior: 'smooth' }); }}><PlayCircle size={24} />See how it works</a></div></div><div className="hero-product" aria-label="Example matching connections"><div className="preview-table"><div className="preview-row preview-head"><span>Person</span><span>Company</span><span>Position</span><span /></div>{initialPeople.map(person => <div className="preview-row" key={person.id}><span className="person-cell"><Avatar person={person} /><strong>{person.firstName} {person.lastName}</strong></span><span>{person.company}</span><span>{person.position}</span><CheckCircle size={18} className="match-check" /></div>)}</div></div></main></section><section id="how-it-works" className="how-it-works" aria-label="How it works">{[{ Icon: UploadSimple, title: '1. Upload your CSV', copy: 'Export your connections from LinkedIn and upload your CSV file.' }, { Icon: Tag, title: '2. Choose your tags', copy: 'Select up to five role tags that represent the people you want to find.' }, { Icon: Users, title: '3. Find your people', copy: 'We’ll match your connections with your tags, so you can focus on the right people.' }].map(({ Icon, title, copy }) => <div className="step" key={title}><span className="step-icon"><Icon size={30} /></span><div><h2>{title}</h2><p>{copy}</p></div></div>)}</section><footer className="footer"><span>© 2026 Linktag. All rights reserved.</span><nav aria-label="Footer">{['Privacy', 'Terms', 'Contact'].map(label => <button key={label} onClick={() => onInfo(label)}>{label}</button>)}</nav></footer></div>;
}
function Auth({ register, onComplete }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  function submit(e) { e.preventDefault(); const data = new FormData(e.currentTarget); if (register && data.get('password') !== data.get('confirmPassword')) { setError('Your passwords don’t match. Please try again.'); return; } setError(''); setBusy(true); window.setTimeout(() => { onComplete(register ? data.get('firstName').trim() || 'Heriberto' : 'Heriberto', register); setBusy(false); }, 350); }
  return <main className={`auth-page ${register ? 'registration' : ''}`}><aside className="auth-brand"><Logo /><div className="auth-story"><h1>{register ? <>Make your<br className="desktop-break" /> network work<br className="desktop-break" /> for you.</> : <>Welcome<br className="desktop-break" /> back</>}</h1><p>{register ? 'Create your account, upload your LinkedIn CSV, choose your tags, and find the people who matter.' : 'Sign in to continue finding the right people in your network.'}</p></div><img className="tag-art" src="/assets/tag-art.png" alt="" /></aside><section className="auth-content"><form className="auth-form" onSubmit={submit}><h2 className="sr-only">{register ? 'Create your account' : 'Sign in to Linktag'}</h2>{register && <><label className="field">First name<input name="firstName" autoComplete="given-name" placeholder="First name" required maxLength={50} /></label><label className="field">Last name<input name="lastName" autoComplete="family-name" placeholder="Last name" required maxLength={50} /></label></>}<label className="field">Email<input type="email" name="email" autoComplete="email" placeholder="you@example.com" required /></label><Password name="password" label="Password" autoComplete={register ? 'new-password' : 'current-password'} minLength={register ? 8 : undefined} placeholder={register ? 'At least 8 characters' : 'Enter your password'} />{register && <Password name="confirmPassword" label="Confirm password" autoComplete="new-password" minLength={8} placeholder="Re-enter your password" />}{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy ? 'Opening your workspace…' : register ? 'Create account' : 'Sign in'}</Button><p className="auth-switch">{register ? 'Already have an account?' : 'New to Linktag?'} <a href={register ? '#signin' : '#register'}>{register ? 'Sign in' : 'Create an account'}</a></p><p className="demo-note">Interactive preview. Use sample details, not your real password.</p></form></section></main>;
}
function Detail({ person, onEdit }) { return <aside className="contact-detail" aria-label="Contact details"><div className="detail-person"><Avatar person={person} large /><div><h2>{person.firstName} {person.lastName}</h2><p>{person.position}<br />at {person.company}</p></div></div><p className="email-line"><EnvelopeSimple size={20} /><span>{person.email || 'No email added'}</span></p><section><h3>About</h3><p>{person.bio || 'No bio yet. Add a few details to remember this connection.'}</p></section><section><h3>Notes</h3><p className="notes-copy">{person.notes || 'No notes yet. Keep useful context about this connection here.'}</p></section><Button variant="outline" onClick={onEdit}>Edit details</Button></aside>; }
function Dashboard({ people, tags, name, onTags, onEdit, onSignout, selected, setSelected }) {
  const matches = filterPeople(people, tags); const person = matches.find(p => p.id === selected) || matches[0];
  return <div className="dashboard"><aside className="sidebar"><Logo small /><nav aria-label="Workspace"><a href="#dashboard" className="active" aria-current="page"><Users size={21} />Recommendations</a><button onClick={onTags}><Tag size={21} />Update tags</button></nav><button className="signout" onClick={onSignout}><SignOut size={21} />Sign out</button></aside><main className="workspace"><header className="workspace-header"><span className="greeting">Welcome back, {name}</span><details className="account"><summary><Users size={18} /><span>{name}</span><CaretDown size={14} /></summary><div className="account-menu"><button onClick={onSignout}><SignOut size={18} />Sign out</button></div></details></header><div className="workspace-grid"><section className="recommendations"><h1>Your recommendations</h1><div className="tag-toolbar"><div><p>Selected tags <span>({tags.length} of 5)</span></p><div className="tag-list">{tags.map(tag => <span className="tag-chip" key={tag}>{tag}</span>)}{!tags.length && <span className="muted">Choose tags to find your people.</span>}</div></div><Button onClick={onTags}>Update tags</Button></div>{matches.length ? <table className="connections"><thead><tr><th>Person</th><th>Company</th><th>Position</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{matches.map(p => <tr key={p.id} className={person.id === p.id ? 'selected' : ''} onClick={() => setSelected(p.id)}><td><button className="person-button" aria-pressed={person.id === p.id} onClick={() => setSelected(p.id)}><Avatar person={p} /><span>{p.firstName} {p.lastName}</span></button></td><td>{p.company}</td><td>{p.position}</td><td><CaretRight size={17} aria-hidden="true" /></td></tr>)}</tbody></table> : <div className="empty-state"><Users size={38} /><h2>{tags.length ? 'No connections match yet' : 'Start with a role tag'}</h2><p>{tags.length ? 'Try a broader role or choose another tag.' : 'Choose up to five roles to see relevant connections.'}</p><Button variant="outline" onClick={onTags}>Choose your tags</Button></div>}</section>{person && <Detail person={person} onEdit={() => onEdit(person)} />}</div></main></div>;
}
function TagsModal({ tags, onSave, onClose }) {
  const [draft, setDraft] = useState(tags); const [value, setValue] = useState(''); const [error, setError] = useState('');
  function add(e) { e.preventDefault(); const next = value.trim(); if (!next) return; if (draft.length >= 5) { setError('You can choose up to five tags. Remove one to add another.'); return; } if (draft.some(t => t.toLowerCase() === next.toLowerCase())) { setError('That tag is already selected.'); return; } setDraft([...draft, next]); setValue(''); setError(''); }
  return <Modal title="Find your people" onClose={onClose}><p className="modal-description">Choose up to five roles. Your recommendations will match any of these tags.</p><p className="tag-count">Your role tags · {draft.length} of 5</p><div className="editable-tags">{draft.map(tag => <span className="tag-chip" key={tag}>{tag}<button aria-label={`Remove ${tag}`} onClick={() => { setDraft(draft.filter(t => t !== tag)); setError(''); }}><X size={16} /></button></span>)}</div><form onSubmit={add} className="add-tag"><label className="field">Add a role<input name="tag" placeholder="e.g. Software Engineer" value={value} maxLength={50} onChange={e => setValue(e.target.value)} /></label><Button variant="outline" type="submit" disabled={!value.trim()}>Add</Button></form>{error && <p className="form-error" role="alert">{error}</p>}<div className="suggestions"><span>Try a role</span>{['Software Engineer', 'Product Manager', 'UX Designer', 'Recruiter', 'Founder'].filter(t => !draft.some(d => d.toLowerCase() === t.toLowerCase())).map(tag => <button disabled={draft.length === 5} key={tag} onClick={() => { setDraft([...draft, tag]); setError(''); }}>{tag}</button>)}</div><div className="modal-actions"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button onClick={() => onSave(draft)}>Apply tags</Button></div></Modal>;
}
function EditModal({ person, onSave, onClose }) { return <Modal title="Edit connection" onClose={onClose} wide><form onSubmit={e => { e.preventDefault(); onSave({ ...person, ...Object.fromEntries(new FormData(e.currentTarget)) }); }}><div className="edit-grid">{[['firstName', 'First name'], ['lastName', 'Last name'], ['company', 'Company'], ['position', 'Position'], ['email', 'Email']].map(([key, label]) => <label className="field" key={key}>{label}<input name={key} defaultValue={person[key]} type={key === 'email' ? 'email' : 'text'} required={key !== 'email'} maxLength={120} /></label>)}<label className="field full">About<textarea name="bio" rows={3} defaultValue={person.bio} maxLength={1000} /></label><label className="field full">Notes<textarea name="notes" rows={4} defaultValue={person.notes} maxLength={2000} /></label></div><p className="demo-note">Changes stay in this preview until you reload.</p><div className="modal-actions"><Button variant="quiet" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Save changes</Button></div></form></Modal>; }
function ImportModal({ onImport, onClose }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function upload(e) { const file = e.target.files?.[0]; if (!file) return; setBusy(true); try { if (file.size > 5 * 1024 * 1024) throw new Error('Choose a CSV smaller than 5 MB.'); const people = parseConnections(await file.text()); onImport(people); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <Modal title="Bring your network into focus" onClose={onClose}><p className="modal-description">Your demo workspace is ready. Upload a LinkedIn connections CSV or explore with our sample connections.</p><label className="upload-zone"><UploadSimple size={35} /><strong>{busy ? 'Reading your file…' : 'Choose a connections CSV'}</strong><span>CSV file · up to 5 MB · processed only in this browser</span><input type="file" accept=".csv,text/csv" onChange={upload} disabled={busy} /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><Button onClick={() => onImport(initialPeople)}>Use sample connections <ArrowRight size={18} /></Button></div></Modal>;
}
export function App() {
  const [route, setRoute] = useState(getRoute); const [name, setName] = useState('Heriberto'); const [people, setPeople] = useState(initialPeople); const [tags, setTags] = useState(initialTags); const [selected, setSelected] = useState(1); const [modal, setModal] = useState(null); const [editing, setEditing] = useState(null); const [toast, setToast] = useState('');
  useEffect(() => { const handler = () => { if (location.hash === '#page-content') return; setRoute(getRoute()); setModal(null); window.scrollTo(0, 0); }; window.addEventListener('hashchange', handler); return () => window.removeEventListener('hashchange', handler); }, []);
  useEffect(() => { document.title = `${routes[route]} · Linktag preview`; }, [route]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 3800); return () => clearTimeout(id); }, [toast]);
  function completeAuth(nextName, register) { setName(nextName); location.hash = 'dashboard'; if (register) window.setTimeout(() => setModal('import'), 50); }
  function signout() { setPeople(initialPeople); setTags(initialTags); setSelected(1); setName('Heriberto'); location.hash = 'signin'; setToast('Signed out of the demo workspace.'); }
  return <><a className="skip-link" href="#page-content">Skip to content</a><div id="page-content" tabIndex={-1}>{route === 'home' ? <Home onInfo={setModal} /> : route === 'signin' || route === 'register' ? <Auth key={route} register={route === 'register'} onComplete={completeAuth} /> : <Dashboard people={people} tags={tags} name={name} selected={selected} setSelected={setSelected} onTags={() => setModal('tags')} onEdit={p => { setEditing(p); setModal('edit'); }} onSignout={signout} />}</div><nav className="preview-bar" aria-label="Design preview pages"><span><span className="preview-label">DESIGN PREVIEW</span><span className="preview-note">Demo data only</span></span><div>{Object.entries(routes).map(([key, label]) => <a key={key} href={`#${key}`} aria-current={route === key ? 'page' : undefined}>{label}</a>)}</div></nav>{toast && <div className="toast" role="status"><CheckCircle size={19} />{toast}<button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16} /></button></div>}{modal === 'tags' && <TagsModal tags={tags} onClose={() => setModal(null)} onSave={next => { setTags(next); setModal(null); setToast('Role tags updated.'); }} />}{modal === 'edit' && editing && <EditModal person={editing} onClose={() => setModal(null)} onSave={next => { setPeople(people.map(p => p.id === next.id ? next : p)); setModal(null); setToast('Connection updated in this preview.'); }} />}{modal === 'import' && <ImportModal onClose={() => setModal(null)} onImport={next => { setPeople(next); setSelected(next[0]?.id); setModal('tags'); }} />}{['Privacy', 'Terms', 'Contact'].includes(modal) && <Modal title={modal} onClose={() => setModal(null)}><p className="modal-description">{modal === 'Contact' ? 'This is a design preview, not a live support channel. Contact and support details will be connected when the design is integrated into the app.' : 'This preview does not create accounts or send form data to a server. Demo changes are held in memory and reset when you reload. Production policies will be linked when this design is integrated into the app.'}</p><Button onClick={() => setModal(null)}>Back to Linktag</Button></Modal>}</>;
}
